import res_partner
import sale_order
import insurance_odoo_product_map
import insurance_config_settings
# import insurance_connect
import insurance_claim
import order_save_service
import res_company
import account_invoice
import payment_journal_mapping
# import insurance_disease_code